const talks: Talk[] = [
  {
    Event: "Update Prague Conference 2023",
    Date: "November 2023",
    Location: "Prague, Czech Republic",
    Title: "Intro to Vector Database",
    URL: "https://www.updateconference.net",
  },
  {
    Event: "Build Stuff 2023",
    Date: "November 2023",
    Location: "Vilnius, Lithuania",
    Title: "Intro to Vector Database",
    URL: "https://www.buildstuff.events",
  },
  {
    Event: "Porto Tech Hub",
    Date: "October 2023",
    Location: "Porto, Portugal",
    Title: "Automated testing with Vitest and PlayWright",
    URL: "https://portotechhub.com",
  },
  {
    Event: "Armada JS 2023",
    Date: "October 2023",
    Location: "Novi Sad, Serbia",
    Title: "RsPack and TurboPack",
    URL: "https://armada-js.com",
  },
  {
    Event: "React Alicante 2023",
    Date: "September 2023",
    Location: "Alicante, Spain",
    Title: "tRPC - Better than REST/GraphQL?",
    URL: "https://reactalicante.es",
  },
  {
    Event: "4Developers",
    Date: "September 2023",
    Location: "Gdansk, Poland",
    Title: "GraphQL in Spring Boot 3 and React",
    URL: "https://4developers.org.pl",
  },
  {
    Event: "Shift Conference",
    Date: "September 2023",
    Location: "Zadar, Croatia",
    Title: "RsPack and TurboPack",
    URL: "https://shift.infobip.com",
  },
  {
    Event: "Azure Fest",
    Date: "September 2023",
    Location: "Nieuwegein, Netherlands",
    Title:
      "Building AI-First Apps with Semantic Kernel: The Future of Software Development",
    URL: "https://www.azurefest.nl",
  },
  {
    Event: ".NET Day Switzerland",
    Date: "August 2023",
    Location: "Zurich, Switzerland",
    Title: "Fault Handling with Retry and Circuit Breaker Design Patterns",
    URL: "https://dotnetday.ch",
  },
  {
    Event: "DevBcn 2023",
    Date: "July 2023",
    Location: "Barcelona, Spain",
    Title: "tRPC - Better than REST/GraphQL?",
    URL: "https://www.devbcn.com",
  },
  {
    Event: "VoxxedDays Luxembourg 2023",
    Date: "June 2023",
    Location: "Mondorf-les-Bains, Luxembourg",
    Title: "Turbopack and RsPack for Modern-day JS Bundlers",
    URL: "https://luxembourg.voxxeddays.com",
  },
  {
    Event: "Devoxx Poland 2023",
    Date: "June 2023",
    Location: "Krakow, Poland",
    Title: "Getting Started with Spring Boot Starter GraphQL and Apollo",
    URL: "https://devoxx.pl",
  },
  {
    Event: "DevOps Pro Europe",
    Date: "May 2023",
    Location: "Vilnius, Lithuania",
    Title: "Remix web framework",
    URL: "https://devopspro.lt",
  },
  {
    Event: "Devoxx Greece 2023",
    Date: "May 2023",
    Location: "Athens, Greece",
    Title: "Fault Handling with Retry and circuit breaker design patterns",
    URL: "https://devoxx.gr",
  },
  {
    Event: "MixIT 2023",
    Date: "April 2023",
    Location: "Lyon, France",
    Title: "Turbopack - Rust-based successor to Webpack",
    URL: "https://mixitconf.org/en/",
  },
  {
    Event: "DevDay 2023",
    Date: "March 2023",
    Location: "Mons, Belgium",
    Title: "Remix, the hottest JavaScript framework today",
    URL: "https://www.devday.be",
  },
  {
    Event: "Øredev Developer Conference",
    Date: "November 2022",
    Location: "Malmö, Sweden",
    Title: "Remix, the hottest JavaScript framework today",
    URL: "https://oredev.org/",
  },
  {
    Event: "JS Poland",
    Date: "October 2022",
    Location: "Warsaw, Poland",
    Title: "Getting Started with Pinia in Vuejs 3",
    URL: "https://js-poland.pl/",
  },
  {
    Event: "React Alicante 2022",
    Date: "September 2022",
    Location: "Alicante, Spain",
    Title: "One-stop-shop Redux toolkit",
    URL: "https://reactalicante.es/",
  },
  {
    Event: "PyCon Estonia 2022",
    Date: "August 2022",
    Location: "Tallinn, Estonia",
    Title:
      "Fault Handling with retry and circuit breaker design patterns in microservices architecture",
    URL: "https://pycon.ee/",
  },
  {
    Event: "Voxxed Days Thessaloniki",
    Date: "June 2022",
    Location: "Thessaloniki, Greece",
    Title: "Getting Started with Spring Boot Starter GraphQL and Apollo",
    URL: "https://voxxeddays.com/thessaloniki/",
  },
  {
    Event: "enterJS 2022",
    Date: "June 2022",
    Location: "Darmstadt, Germany",
    Title: "Vite – The Next Generation Frontend Tooling",
    URL: "https://enterjs.de/",
  },
  {
    Event: "THAT Conference 2022",
    Date: "May 2022",
    Location: "Texas, USA",
    Title: "The 9 Most Common Security Threats to Mobile Devices",
    URL: "https://that.us/activities/ACdUS15w49gawdj8ouNF",
  },
  {
    Event: "Neos Conference 2022",
    Date: "April 2022",
    Location: "Dresden, Germany",
    Title: "Redux Toolkit",
    URL: "https://www.neoscon.io/",
  },
  {
    Event: "Basta 2022",
    Date: "February 2022",
    Location: "Frankfurt, Germany",
    Title: "MAUI – the Evolution of Xamarin.Forms",
    URL: "https://basta.net/",
  },
  {
    Event: "HoneyCon2021",
    Date: "November 13, 2021",
    Location: "Spain",
    Title: "Most common vulnerabilities in web and mobile application",
    URL: "https://honeycon.eu/",
  },
  {
    Event: "iJS",
    Date: "October 2021",
    Location: "Munich, Germany",
    Title: "Vite - the next-gen frontend tooling",
    URL: "https://javascript-conference.com/munich/program-munich/",
  },
  {
    Event: "React Advanced",
    Date: "October 2021",
    Location: "London",
    Title: "Vite - the next-gen frontend tooling",
    URL: "https://reactadvanced.com/",
  },
  {
    Event: "Droidcon",
    Date: "October 2021",
    Location: "Berlin, Germany",
    Title: "The 9 Most Common Security Threats to Mobile Devices in 2021",
    URL: "https://www.berlin.droidcon.com/",
  },
  {
    Event: "JavaCro 2021",
    Date: "October 2021",
    Location: "Rovinj, Croatia",
    Title: "Software testing",
    URL: "https://2021.javacro.hr/eng",
  },
  {
    Event: "Web Summer Camp 2021",
    Date: "September 2021",
    Location: "Sibenik, Croatia",
    Title: "TypeScript from zero to hero",
    URL: "https://2021.websummercamp.com/",
  },
  {
    Event: "Web Developer Conference 2021",
    Date: "June 28-29, 2021",
    Location: "Berlin",
    Title: "Vuejs 3 and Vuex 4",
    URL: "https://www.web-developer-conference.de",
  },
  {
    Event: "DevDays Europe 2021",
    Date: "June 10, 2021",
    Location: "Online",
    Title: "NGRX in Angular",
    URL: "https://devdays.lt/",
  },
  {
    Event: "Basta Hybrid Konferenz 2021",
    Date: "Feb 15-19, 2021",
    Location: "Frankfurt",
    Title: "Migrating from ASP.NET Core REST to ASP.NET GraphQL",
    URL: "https://basta.net/net-framework-c/migrating-from-asp-net-core-rest-to-asp-net-graphql",
  },
  {
    Event: "Devoxx Ukraine 2020",
    Date: "Nov 6-7, 2020",
    Location: "online",
    Title: "Intro to PASETO",
    URL: "https://devoxx.com.ua/",
  },
  {
    Event: "Scenic City 2020",
    Date: "Nov 6, 2020",
    Location: "online",
    Title: "Developers’ Guide to Web Security",
    URL: "https://sceniccitysummit.com/",
  },
  {
    Event: "iJS Munich 2020",
    Date: "Oct. 26-30, 2020",
    Location: "Munich (hybrid)",
    Title: "Svelte, cybernetically enhanced web apps",
    URL: "https://javascript-conference.com/munich/program-munich/",
  },
  {
    Event: "All Things Open 2020",
    Date: "Oct 19-20, 2020",
    Location: "online",
    Title:
      "Automating your infrastructure deployments in the Cloud with Terraform and Azure Pipelines",
    URL: "https://2020.allthingsopen.org/speakers/",
  },
  {
    Event: "NDC Sydney",
    Date: "September 15, 2020",
    Location: "converted to online",
    Title: "Svelte, cybernetically enhanced web apps",
    URL: "https://ndcsydney.com/",
  },
  {
    Event: "Devoxx Ukraine 2020",
    Date: "November 6-7, 2020",
    Location: "Ukraine (converted online)",
    Title:
      "Developer’s Guide to Common Vulnerabilities and How to Prevent Them",
    URL: "https://devoxx.com.ua/",
  },
  {
    Event: "Swiss Lightning Talks",
    Date: "September 15, 2020",
    Location: "online",
    Title: "IaC using C# (Pulumi)",
    URL: "https://www.meetup.com/dotnet-zurich/events/270420173/",
  },
  {
    Event: "React Virtual Conference",
    Date: "September 11, 2020",
    Location: "online",
    Title: "Sneak Peak of React Router V6",
    URL: "https://www.2020twenty.net/react/#speakers",
  },
  {
    Event: "iJS International JavaScript Conference 2020",
    Date: "September 2-4, 2020",
    Location: "Victoria, London (hybrid conference)",
    Title: "Getting Started with Vue and Vuex State Management",
    URL: "https://javascript-conference.com/",
  },
  {
    Event: "Code PaLOUsa 2020",
    Date: "August 19-21, 2020",
    Location: "Louisville, KY (converted to online)",
    Title: "Migrating REST to GraphQL",
    URL: "http://www.codepalousa.com/",
  },
  {
    Event: "BSides Budapest International IT Security Conference",
    Date: "May 28, 2020",
    Location: "Budapest, Hungary (converted to virtual)",
    Title: "Introduction to PASETO (platform-agnostic security tokens)",
    URL: "https://2020.bsidesbud.com/",
  },
  {
    Event: "ngVikings 2020",
    Date: "May 25-26, 2020",
    Location: "Oslo, Norway (converted to virtual)",
    Title: "Simplifying NgRx",
    URL: "https://ngvikings.org/",
  },
  {
    Event: "Cloud DeveloperDays 2020",
    Date: "May 25-26, 2020",
    Location: "Krakow, Poland (converted to virtual)",
    Title: "Terraform and DevOps Pipeline",
    URL: "https://cloud.developerdays.pl/",
  },
  {
    Event: "AzureDay Poland",
    Date: "March 3, 2020",
    Location: "Warsaw, Poland",
    Title:
      "Automating your infrastructure deployments in the Cloud with Terraform and Azure Pipelines",
    URL: "https://azureday.pro/",
  },
  {
    Event: "The European Swift Conference",
    Date: "February 3, 2020",
    Location: "Paris, France",
    Title: "Sign In with Apple: Learn About the New Identity Provider",
    URL: "https://www.dotswift.io/",
  },
  {
    Event: "NDC London 2020",
    Date: "January 27-31, 2020",
    Location: "Westminster, London",
    Title: "Svelte, cybernetically enhanced web apps",
    URL: "https://ndc-london.com/",
  },
  {
    Event: "Frontend Con 2019",
    Date: "November 27-28, 2019",
    Location: "Warsaw, Poland",
    Title: "Svelte, cybernetically enhanced website",
    URL: "https://frontend-con.io/",
  },
  {
    Event: "SciFiDevCon",
    Date: "June 29-30, 2020",
    Location: "Virtual",
    Title:
      "Automating your infrastructure deployments in Azure, AWS, and GCP using Terraform",
    URL: "https://www.scifidevcon.com/",
  },
  {
    Event: "JNation 2020",
    Date: "June 2, 2020",
    Location: "Coimbra, Portugal (converted to virtual)",
    Title: "Terraform in Azure, AWS, and Googe Cloud",
    URL: "https://2020.jnation.pt/speakers/",
  },
  {
    Event: "Vue Conf Toronto",
    Date: "November 11-12, 2019",
    Location: "Toronto, Canada",
    Title: "GraphQL using Hasura and VueJS app",
    URL: "https://vuetoronto.com/",
  },
  {
    Event: "Dev Up Conference",
    Date: "October 14-16, 2019",
    Location: "St.Louis, Missouri, USA",
    Title: "Full-stack TypeScript using Angular, NestJS, TypeORM, and Auth0",
    URL: "https://www.devupconf.org/",
  },
  {
    Event: "KharkivJS",
    Date: "October 5-6",
    Location: "Kharkiv, Ukraine",
    Title: "Svelte, a modern JavaScript library",
    URL: "http://kharkivjs.org/",
  },
  {
    Event: "ChainReact Conf",
    Date: "July 12-13, 2019",
    Location: "Portland, Oregon, USA",
    Title: "Getting started with Mobx State Tree in React and React Native",
    URL: "https://infinite.red/ChainReactConf",
  },
  {
    Event: "Landing Festival Lisbon",
    Date: "June 29-30, 2019",
    Location: "Lisbon, Portugal",
    Title: "Getting started with Mobx State Tree in React and React Native",
    URL: "https://landingfestival.com/speakers/devlin-duldulao/",
  },
  {
    Event: "SoftCon",
    Date: "October 24, 2018",
    Location: "Makati, Philippines",
    Title: "Progressive Web Apps, the future of web apps",
    URL: "https://www.softcon.ph/devlin-duldulao",
  },
  {
    Event: "WordCamp",
    Date: "September 8, 2018",
    Location: "Makati, Philippines",
    Title: "Progressive Web Apps, the future of web apps",
    URL: "https://2018.manila.wordcamp.org/speaker/devlin-duldulao/",
  },
];

export default talks;

type Talk = {
  Event: string;
  Date: string;
  Location: string;
  Title: string;
  URL: string;
};
