const talks: Talk[] = [
  {
    event: "iJS Singapore",
    date: "November 2024",
    location: "Singapore",
    title: "AnalogJS BFF pattern",
    url: "https://javascript-conference.com/singapore",
  },
  {
    event: "Update Prague Conference",
    date: "November 2024",
    location: "Prague, Czech Republic",
    title: "AnalogJS and Remix BFF pattern",
    url: "https://www.updateconference.net",
  },
  {
    event: "Heapcon",
    date: "November 2024",
    location: "Belgrade, Serbia",
    title: "AnalogJS BFF pattern",
    url: "https://heapcon.io",
  },
  {
    event: "React Advanced London",
    date: "October 2024",
    location: "Online",
    title: "Is Bun really that fast?",
    url: "https://reactadvanced.com",
  },
  {
    event: "TDC 2024",
    date: "October 2024",
    location: "Trondheim, Norway",
    title: "Fault handling with Retry and Circuit Breaker Design Patterns",
    url: "https://2024.trondheimdc.no",
  },
  {
    event: "Voxxed Days Thessaloniki",
    date: "October 2024",
    location: "Thessaloniki, Greece",
    title: "Building Next-Gen Cross-Platform Apps with Tauri 2.0",
    url: "https://voxxeddays.com/thessaloniki/",
  },
  {
    event: "NG DE - Angular Conference 2024",
    date: "October 2024",
    location: "Bonn, Germany",
    title: "Angular Tanstack Query",
    url: "https://ng-de.org",
  },
  {
    event: "React Alicante 2024",
    date: "September 2024",
    location: "Alicante, Spain",
    title: "Tanstack Router",
    url: "https://reactalicante.es",
  },
  {
    event: "NDC Oslo 2024",
    date: "June 2024",
    location: "Oslo, Norway",
    title: "Freshly Toasted: How Bun stable version is Heating Up JS & TS",
    url: "https://ndcoslo.com",
  },
  {
    event: "DevTalks Romania 2024",
    date: "May 2024",
    location: "Bucharest, Romania",
    title: "Building Next-Gen Cross-Platform Apps with Tauri 2.0",
    url: "https://www.devtalks.ro",
  },
  {
    event: "Devoxx UK 2024",
    date: "May 2024",
    location: "London, UK",
    title: "Freshly Toasted: How Bun stable version is Heating Up JS & TS",
    url: "https://www.devoxx.co.uk",
  },
  {
    event: "Update Prague Conference 2023",
    date: "November 2023",
    location: "Prague, Czech Republic",
    title: "Intro to Vector Database",
    url: "https://www.updateconference.net",
  },
  {
    event: "Build Stuff 2023",
    date: "November 2023",
    location: "Vilnius, Lithuania",
    title: "Intro to Vector Database",
    url: "https://www.buildstuff.events",
  },
  {
    event: "Porto Tech Hub",
    date: "October 2023",
    location: "Porto, Portugal",
    title: "Automated testing with Vitest and PlayWright",
    url: "https://portotechhub.com",
  },
  {
    event: "Armada JS 2023",
    date: "October 2023",
    location: "Novi Sad, Serbia",
    title: "RsPack and TurboPack",
    url: "https://armada-js.com",
  },
  {
    event: "React Alicante 2023",
    date: "September 2023",
    location: "Alicante, Spain",
    title: "tRPC - Better than REST/GraphQL?",
    url: "https://reactalicante.es",
  },
  {
    event: "4Developers",
    date: "September 2023",
    location: "Gdansk, Poland",
    title: "GraphQL in Spring Boot 3 and React",
    url: "https://4developers.org.pl",
  },
  {
    event: "Shift Conference",
    date: "September 2023",
    location: "Zadar, Croatia",
    title: "RsPack and TurboPack",
    url: "https://shift.infobip.com",
  },
  {
    event: "Azure Fest",
    date: "September 2023",
    location: "Nieuwegein, Netherlands",
    title:
      "Building AI-First Apps with Semantic Kernel: The Future of Software Development",
    url: "https://www.azurefest.nl",
  },
  {
    event: ".NET Day Switzerland",
    date: "August 2023",
    location: "Zurich, Switzerland",
    title: "Fault Handling with Retry and Circuit Breaker Design Patterns",
    url: "https://dotnetday.ch",
  },
  {
    event: "DevBcn 2023",
    date: "July 2023",
    location: "Barcelona, Spain",
    title: "tRPC - Better than REST/GraphQL?",
    url: "https://www.devbcn.com",
  },
  {
    event: "VoxxedDays Luxembourg 2023",
    date: "June 2023",
    location: "Mondorf-les-Bains, Luxembourg",
    title: "Turbopack and RsPack for Modern-day JS Bundlers",
    url: "https://luxembourg.voxxeddays.com",
  },
  {
    event: "Devoxx Poland 2023",
    date: "June 2023",
    location: "Krakow, Poland",
    title: "Getting Started with Spring Boot Starter GraphQL and Apollo",
    url: "https://devoxx.pl",
  },
  {
    event: "DevOps Pro Europe",
    date: "May 2023",
    location: "Vilnius, Lithuania",
    title: "Remix web framework",
    url: "https://devopspro.lt",
  },
  {
    event: "Devoxx Greece 2023",
    date: "May 2023",
    location: "Athens, Greece",
    title: "Fault Handling with Retry and circuit breaker design patterns",
    url: "https://devoxx.gr",
  },
  {
    event: "MixIT 2023",
    date: "April 2023",
    location: "Lyon, France",
    title: "Turbopack - Rust-based successor to Webpack",
    url: "https://mixitconf.org/en/",
  },
  {
    event: "DevDay 2023",
    date: "March 2023",
    location: "Mons, Belgium",
    title: "Remix, the hottest JavaScript framework today",
    url: "https://www.devday.be",
  },
  {
    event: "Øredev Developer Conference",
    date: "November 2022",
    location: "Malmö, Sweden",
    title: "Remix, the hottest JavaScript framework today",
    url: "https://oredev.org/",
  },
  {
    event: "JS Poland",
    date: "October 2022",
    location: "Warsaw, Poland",
    title: "Getting Started with Pinia in Vuejs 3",
    url: "https://js-poland.pl/",
  },
  {
    event: "React Alicante 2022",
    date: "September 2022",
    location: "Alicante, Spain",
    title: "One-stop-shop Redux toolkit",
    url: "https://reactalicante.es/",
  },
  {
    event: "PyCon Estonia 2022",
    date: "August 2022",
    location: "Tallinn, Estonia",
    title:
      "Fault Handling with retry and circuit breaker design patterns in microservices architecture",
    url: "https://pycon.ee/",
  },
  {
    event: "Voxxed Days Thessaloniki",
    date: "June 2022",
    location: "Thessaloniki, Greece",
    title: "Getting Started with Spring Boot Starter GraphQL and Apollo",
    url: "https://voxxeddays.com/thessaloniki/",
  },
  {
    event: "enterJS 2022",
    date: "June 2022",
    location: "Darmstadt, Germany",
    title: "Vite – The Next Generation Frontend Tooling",
    url: "https://enterjs.de/",
  },
  {
    event: "THAT Conference 2022",
    date: "May 2022",
    location: "Texas, USA",
    title: "The 9 Most Common Security Threats to Mobile Devices",
    url: "https://that.us/activities/ACdUS15w49gawdj8ouNF",
  },
  {
    event: "Neos Conference 2022",
    date: "April 2022",
    location: "Dresden, Germany",
    title: "Redux Toolkit",
    url: "https://www.neoscon.io/",
  },
  {
    event: "Basta 2022",
    date: "February 2022",
    location: "Frankfurt, Germany",
    title: "MAUI – the Evolution of Xamarin.Forms",
    url: "https://basta.net/",
  },
  {
    event: "HoneyCon2021",
    date: "November 13, 2021",
    location: "Spain",
    title: "Most common vulnerabilities in web and mobile application",
    url: "https://honeycon.eu/",
  },
  {
    event: "iJS",
    date: "October 2021",
    location: "Munich, Germany",
    title: "Vite - the next-gen frontend tooling",
    url: "https://javascript-conference.com/munich/program-munich/",
  },
  {
    event: "React Advanced",
    date: "October 2021",
    location: "London",
    title: "Vite - the next-gen frontend tooling",
    url: "https://reactadvanced.com/",
  },
  {
    event: "Droidcon",
    date: "October 2021",
    location: "Berlin, Germany",
    title: "The 9 Most Common Security Threats to Mobile Devices in 2021",
    url: "https://www.berlin.droidcon.com/",
  },
  {
    event: "JavaCro 2021",
    date: "October 2021",
    location: "Rovinj, Croatia",
    title: "Software testing",
    url: "https://2021.javacro.hr/eng",
  },
  {
    event: "Web Summer Camp 2021",
    date: "September 2021",
    location: "Sibenik, Croatia",
    title: "TypeScript from zero to hero",
    url: "https://2021.websummercamp.com/",
  },
  {
    event: "Web Developer Conference 2021",
    date: "June 28-29, 2021",
    location: "Berlin",
    title: "Vuejs 3 and Vuex 4",
    url: "https://www.web-developer-conference.de",
  },
  {
    event: "DevDays Europe 2021",
    date: "June 10, 2021",
    location: "Online",
    title: "NGRX in Angular",
    url: "https://devdays.lt/",
  },
  {
    event: "Basta Hybrid Konferenz 2021",
    date: "Feb 15-19, 2021",
    location: "Frankfurt",
    title: "Migrating from ASP.NET Core REST to ASP.NET GraphQL",
    url: "https://basta.net/net-framework-c/migrating-from-asp-net-core-rest-to-asp-net-graphql",
  },
  {
    event: "Devoxx Ukraine 2020",
    date: "Nov 6-7, 2020",
    location: "online",
    title: "Intro to PASETO",
    url: "https://devoxx.com.ua/",
  },
  {
    event: "Scenic City 2020",
    date: "Nov 6, 2020",
    location: "online",
    title: "Developers’ Guide to Web Security",
    url: "https://sceniccitysummit.com/",
  },
  {
    event: "iJS Munich 2020",
    date: "Oct. 26-30, 2020",
    location: "Munich (hybrid)",
    title: "Svelte, cybernetically enhanced web apps",
    url: "https://javascript-conference.com/munich/program-munich/",
  },
  {
    event: "All Things Open 2020",
    date: "Oct 19-20, 2020",
    location: "online",
    title:
      "Automating your infrastructure deployments in the Cloud with Terraform and Azure Pipelines",
    url: "https://2020.allthingsopen.org/speakers/",
  },
  {
    event: "NDC Sydney",
    date: "September 15, 2020",
    location: "converted to online",
    title: "Svelte, cybernetically enhanced web apps",
    url: "https://ndcsydney.com/",
  },
  {
    event: "Devoxx Ukraine 2020",
    date: "November 6-7, 2020",
    location: "Ukraine (converted online)",
    title:
      "Developer’s Guide to Common Vulnerabilities and How to Prevent Them",
    url: "https://devoxx.com.ua/",
  },
  {
    event: "Swiss Lightning Talks",
    date: "September 15, 2020",
    location: "online",
    title: "IaC using C# (Pulumi)",
    url: "https://www.meetup.com/dotnet-zurich/events/270420173/",
  },
  {
    event: "React Virtual Conference",
    date: "September 11, 2020",
    location: "online",
    title: "Sneak Peak of React Router V6",
    url: "https://www.2020twenty.net/react/#speakers",
  },
  {
    event: "iJS International JavaScript Conference 2020",
    date: "September 2-4, 2020",
    location: "Victoria, London (hybrid conference)",
    title: "Getting Started with Vue and Vuex State Management",
    url: "https://javascript-conference.com/",
  },
  {
    event: "Code PaLOUsa 2020",
    date: "August 19-21, 2020",
    location: "Louisville, KY (converted to online)",
    title: "Migrating REST to GraphQL",
    url: "http://www.codepalousa.com/",
  },
  {
    event: "BSides Budapest International IT Security Conference",
    date: "May 28, 2020",
    location: "Budapest, Hungary (converted to virtual)",
    title: "Introduction to PASETO (platform-agnostic security tokens)",
    url: "https://2020.bsidesbud.com/",
  },
  {
    event: "ngVikings 2020",
    date: "May 25-26, 2020",
    location: "Oslo, Norway (converted to virtual)",
    title: "Simplifying NgRx",
    url: "https://ngvikings.org/",
  },
  {
    event: "Cloud DeveloperDays 2020",
    date: "May 25-26, 2020",
    location: "Krakow, Poland (converted to virtual)",
    title: "Terraform and DevOps Pipeline",
    url: "https://cloud.developerdays.pl/",
  },
  {
    event: "AzureDay Poland",
    date: "March 3, 2020",
    location: "Warsaw, Poland",
    title:
      "Automating your infrastructure deployments in the Cloud with Terraform and Azure Pipelines",
    url: "https://azureday.pro/",
  },
  {
    event: "The European Swift Conference",
    date: "February 3, 2020",
    location: "Paris, France",
    title: "Sign In with Apple: Learn About the New Identity Provider",
    url: "https://www.dotswift.io/",
  },
  {
    event: "NDC London 2020",
    date: "January 27-31, 2020",
    location: "Westminster, London",
    title: "Svelte, cybernetically enhanced web apps",
    url: "https://ndc-london.com/",
  },
  {
    event: "Frontend Con 2019",
    date: "November 27-28, 2019",
    location: "Warsaw, Poland",
    title: "Svelte, cybernetically enhanced website",
    url: "https://frontend-con.io/",
  },
  {
    event: "SciFiDevCon",
    date: "June 29-30, 2020",
    location: "Virtual",
    title:
      "Automating your infrastructure deployments in Azure, AWS, and GCP using Terraform",
    url: "https://www.scifidevcon.com/",
  },
  {
    event: "JNation 2020",
    date: "June 2, 2020",
    location: "Coimbra, Portugal (converted to virtual)",
    title: "Terraform in Azure, AWS, and Googe Cloud",
    url: "https://2020.jnation.pt/speakers/",
  },
  {
    event: "Vue Conf Toronto",
    date: "November 11-12, 2019",
    location: "Toronto, Canada",
    title: "GraphQL using Hasura and VueJS app",
    url: "https://vuetoronto.com/",
  },
  {
    event: "Dev Up Conference",
    date: "October 14-16, 2019",
    location: "St.Louis, Missouri, USA",
    title: "Full-stack TypeScript using Angular, NestJS, TypeORM, and Auth0",
    url: "https://www.devupconf.org/",
  },
  {
    event: "KharkivJS",
    date: "October 5-6",
    location: "Kharkiv, Ukraine",
    title: "Svelte, a modern JavaScript library",
    url: "http://kharkivjs.org/",
  },
  {
    event: "ChainReact Conf",
    date: "July 12-13, 2019",
    location: "Portland, Oregon, USA",
    title: "Getting started with Mobx State Tree in React and React Native",
    url: "https://infinite.red/ChainReactConf",
  },
  {
    event: "Landing Festival Lisbon",
    date: "June 29-30, 2019",
    location: "Lisbon, Portugal",
    title: "Getting started with Mobx State Tree in React and React Native",
    url: "https://landingfestival.com/speakers/devlin-duldulao/",
  },
  {
    event: "SoftCon",
    date: "October 24, 2018",
    location: "Makati, Philippines",
    title: "Progressive Web Apps, the future of web apps",
    url: "https://www.softcon.ph/devlin-duldulao",
  },
  {
    event: "WordCamp",
    date: "September 8, 2018",
    location: "Makati, Philippines",
    title: "Progressive Web Apps, the future of web apps",
    url: "https://2018.manila.wordcamp.org/speaker/devlin-duldulao/",
  },
];

export default talks;

export type Talk = {
  event: string;
  date: string;
  location: string;
  title: string;
  url: string;
};
